# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i73n6KK2J_AnYnk312pETk4m8S76DiKV
"""

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt

# ---------------- FUNCTIONS ---------------- #

def analyze_dataset(file):
    df = pd.read_csv(file.name)

    preview = df.head(10)

    eda = f"""
Rows: {df.shape[0]}
Columns: {df.shape[1]}

Mean Marks: {df['Marks'].mean():.2f}
Median Marks: {df['Marks'].median()}
Mode Marks: {df['Marks'].mode()[0]}
"""

    # -------- Semester-wise average -------- #
    sem_avg = df.groupby("Semester")["Marks"].mean()
    fig1, ax1 = plt.subplots()
    ax1.plot(sem_avg.index, sem_avg.values, marker="o")
    ax1.set_title("Semester-wise Performance")
    ax1.set_xlabel("Semester")
    ax1.set_ylabel("Average Marks")

    # -------- Semester-wise Subject Performance -------- #
    fig2, ax2 = plt.subplots(figsize=(8,5))
    df.pivot_table(values="Marks", index="Subject", columns="Semester").plot(kind="bar", ax=ax2)
    ax2.set_title("Semester-wise Subject Performance")
    ax2.set_ylabel("Marks")

    # -------- Pass Fail -------- #
    result = df["Result"].value_counts()
    fig3, ax3 = plt.subplots()
    ax3.pie(result, labels=result.index, autopct="%1.1f%%")
    ax3.set_title("Pass vs Fail")

    # -------- Subject-wise Semester Trend -------- #
    fig4, ax4 = plt.subplots()
    for subject in df["Subject"].unique():
        temp = df[df["Subject"] == subject]
        ax4.plot(temp["Semester"], temp["Marks"], marker="o", label=subject)

    ax4.set_title("Subject-wise Semester Trend")
    ax4.set_xlabel("Semester")
    ax4.set_ylabel("Marks")
    ax4.legend()

    return preview, eda, fig1, fig2, fig3, fig4


# ---------------- UI ---------------- #

with gr.Blocks() as app:
    gr.Markdown("## 📊 Student Performance Analysis System")

    with gr.Row():
        with gr.Column(scale=1):
            file = gr.File(label="📂 Upload Student CSV")
            analyze_btn = gr.Button("🔍 Analyze Dataset")
            dataset = gr.Dataframe(label="📄 Dataset Preview")
            eda_box = gr.Textbox(label="📌 EDA Summary", lines=6)

        with gr.Column(scale=2):
            sem_graph = gr.Plot()
            subject_sem_bar = gr.Plot()
            pie = gr.Plot()
            subject_sem_graph = gr.Plot()

    analyze_btn.click(
        analyze_dataset,
        inputs=file,
        outputs=[dataset, eda_box, sem_graph, subject_sem_bar, pie, subject_sem_graph]
    )

app.launch()
#link to my ui:https://huggingface.co/spaces/priyam1407/Student_exam_per

