# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTqnNdjlKyWLdK4YrOyJz8vyMovSSSJr

##### grdaio ui student per #####
"""

!pip install gradio pandas matplotlib

import pandas as pd

df = pd.read_csv("Student_per.csv")
df.head()

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ---------------- FUNCTIONS ---------------- #

def analyze_dataset(file):
    df = pd.read_csv(file.name)

    # Dataset preview
    preview = df.head(10)

    # EDA summary
    eda = f"""
Rows: {df.shape[0]}
Columns: {df.shape[1]}

Mean Marks: {df['Marks'].mean():.2f}
Median Marks: {df['Marks'].median()}
Mode Marks: {df['Marks'].mode()[0]}
"""

    # -------- Semester-wise average (LINE) -------- #
    sem_avg = df.groupby("Semester")["Marks"].mean()
    fig1, ax1 = plt.subplots()
    ax1.plot(sem_avg.index, sem_avg.values, marker="o")
    ax1.set_title("Semester-wise Performance")
    ax1.set_xlabel("Semester")
    ax1.set_ylabel("Average Marks")

    # -------- Semester-wise Subject Performance (BAR) -------- #
    fig2, ax2 = plt.subplots(figsize=(8,5))
    sns.barplot(
        data=df,
        x="Subject",
        y="Marks",
        hue="Semester",
        ax=ax2
    )
    ax2.set_title("Semester-wise Subject Performance")
    ax2.set_xlabel("Subject")
    ax2.set_ylabel("Marks")
    plt.xticks(rotation=45)

    # -------- Pass Fail -------- #
    result = df["Result"].value_counts()
    fig3, ax3 = plt.subplots()
    ax3.pie(result, labels=result.index, autopct="%1.1f%%")
    ax3.set_title("Pass vs Fail")

    # -------- Subject-wise Semester Trend (LINE) -------- #
    fig4, ax4 = plt.subplots()
    sns.lineplot(
        data=df,
        x="Semester",
        y="Marks",
        hue="Subject",
        marker="o",
        ax=ax4
    )
    ax4.set_title("Subject-wise Semester Trend")

    return preview, eda, fig1, fig2, fig3, fig4


# ---------------- UI ---------------- #

with gr.Blocks(theme=gr.themes.Soft()) as app:

    gr.Markdown("## 📊 Student Performance Analysis System")

    with gr.Row():

        # -------- LEFT PANEL -------- #
        with gr.Column(scale=1):
            file = gr.File(label="📂 Upload Student CSV")
            analyze_btn = gr.Button("🔍 Analyze Dataset")

            dataset = gr.Dataframe(label="📄 Dataset Preview")
            eda_box = gr.Textbox(label="📌 EDA Summary", lines=6)

        # -------- RIGHT PANEL -------- #
        with gr.Column(scale=2):
            sem_graph = gr.Plot(label="📈 Semester-wise Performance")
            subject_sem_bar = gr.Plot(label="📚 Semester-wise Subject Performance")
            pie = gr.Plot(label="✅ Pass vs Fail")
            subject_sem_graph = gr.Plot(label="📊 Subject-wise Semester Trend")

    analyze_btn.click(
        analyze_dataset,
        inputs=file,
        outputs=[
            dataset,
            eda_box,
            sem_graph,
            subject_sem_bar,
            pie,
            subject_sem_graph
        ]
    )

app.launch(server_name="0.0.0.0", server_port=7860)

